### PR TITLE
Return before entering complete-popup window

### LINKED ISSUE #5: E994: Not allowed in a popup window, when both vim-hitspop popup-window and complete-popup window are displayed
**Describe the bug**
Vim throws the error `E994: Not allowed in a popup window` when both the `vim-hitspop` popup-window and the `complete-popup` window are displayed during insert-mode completion.

**To reproduce**
1. Run `vim test.vim -S test.vim`, with
   ```vim
   set completeopt+=popup
   set completepopup=border:off,align:menu
   
   function ListMonths()
       call complete(col('.'), [
               \ {'word': 'January',   'info': 'January'},
               \ {'word': 'February',  'info': 'February'},
               \ {'word': 'March',     'info': 'March'},
               \ {'word': 'April',     'info': 'April'},
               \ {'word': 'May',       'info': 'May'},
               \ {'word': 'June',      'info': 'June'},
               \ {'word': 'July',      'info': 'July'},
               \ {'word': 'August',    'info': 'August'},
               \ {'word': 'September', 'info': 'September'},
               \ {'word': 'October',   'info': 'October'},
               \ {'word': 'November',  'info': 'November'},
               \ {'word': 'December',  'info': 'December'}
               \ ])
       return ''
   endfunction
   
   inoremap <C-@> <C-R>=ListMonths()<CR>
   ```
2. Search for a word, for example, enter `/word<cr>`
3. Press `CTRL-SPACE` while in insert-mode and cycle through the completion menu.
4. Result: Vim will print the following error:
   ```
   Error detected while processing WinLeave Autocommands for "*"..function hitspop#clean[4]..<SNR>108_DeletePopupIfExists:
   line    2:
   E994: Not allowed in a popup window
   ```

**Environment**
Vim version `8.2.1980`

### PR DESCRIPTION
**Pull request by bfrg**
Fixes #5.

### CODE REVIEW

**Comment by obcat** [comment]
Merged.

I honestly don't know why this error occurs, but your PR fixes this certainly :)

Thank you! 💛

**Comment by bfrg** [comment]
It looks like Vim leaves the current window (the one where insert-completion was triggered) and temporarily focuses the `complete-popup` window every time the completion-menu is cycled through with `CTRL-N` or `CTRL-P`, i.e. on every `CompleteChanged` event.

You can check it with the following snippet. Run `vim --clean -S test.vim`, with:
```vim
" test.vim
set completeopt=menu,noinsert,noselect,popup

augroup test
    autocmd!
    autocmd WinLeave *
            \ echomsg printf('WinLeave: "%s", win-ID: %d, win_gettype: %s',
            \ expand('<amatch>'),
            \ win_getid(),
            \ win_gettype()
            \ )
augroup END

function ListMonths()
    call complete(col('.'), [
            \ {'word': 'January',   'info': 'January'},
            \ {'word': 'February',  'info': 'February'},
            \ {'word': 'March',     'info': 'March'},
            \ {'word': 'April',     'info': 'April'},
            \ {'word': 'May',       'info': 'May'},
            \ {'word': 'June',      'info': 'June'},
            \ {'word': 'July',      'info': 'July'},
            \ {'word': 'August',    'info': 'August'},
            \ {'word': 'September', 'info': 'September'},
            \ {'word': 'October',   'info': 'October'},
            \ {'word': 'November',  'info': 'November'},
            \ {'word': 'December',  'info': 'December'}
            \ ])
    return ''
endfunction

inoremap <c-@> <C-R>=ListMonths()<cr>
```

This is the output of `:messages` after pressing `CTRL-N` two times:
```
WinLeave: "", win-ID: 1000, win_gettype:
WinLeave: "", win-ID: 1001, win_gettype: popup
WinLeave: "", win-ID: 1000, win_gettype:
WinLeave: "", win-ID: 1001, win_gettype: popup
WinLeave: "", win-ID: 1000, win_gettype:
WinLeave: "", win-ID: 1001, win_gettype: popup
```

I don't know whether this is intentional or a bug.

**Comment by obcat** [comment]
Reproduced. It's too weird.

I found that `WinLeave` is triggered only when the `info popup` appears.

```vim
" test.vim
set completeopt=menu,popup

" To see what happens
set laststatus=2
set cmdheight=2

let s:count = 1
augroup test
  autocmd!
  autocmd WinLeave *
          \   if win_gettype() ==# 'popup'
          \ |   echom printf('Leaving popup...[%d]', s:count)
          \ |   let s:count += 1
          \ | endif
augroup END

function ListMonths()
    call complete(col('.'), [
            \ {'word': 'January'                     },
            \ {'word': 'February'                     },
            \ {'word': 'March',     'info': 'March'},
            \ {'word': 'April',     'info': 'April'},
            \ {'word': 'May'                     },
            \ {'word': 'June'                     },
            \ {'word': 'July',      'info': 'July'},
            \ {'word': 'August',    'info': 'August'},
            \ {'word': 'September'                     },
            \ {'word': 'October'                     },
            \ {'word': 'November',  'info': 'November'},
            \ {'word': 'December',  'info': 'December'}
            \ ])
    return ''
endfunction

inoremap <C-@> <C-R>=ListMonths()<CR>
```

A message like `Leaving popup...[N]` is shown only when the selection move to the item having an `info`.
And the count `N` in the initial message can be `2` or `1`... (It will be `1` after reloading this script.)

**Comment by obcat** [comment]
Fixed in https://github.com/vim/vim/commit/2dfae04f376a58d4c5a801cb652c8eae65900672 :tada:

**Pull request merged**
